language: javascript
addons:
  ssh_known_hosts:
  - "$SERVER"
before_script:
  - echo -e "Host $SERVERntStrictHostKeyChecking non" >> ~/.ssh/config
script:
  - npm install
  - npm run setup
  - npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master
